### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus20/kevinwe-sockets#1]
Well done this week Kevin,

However the clients cannot communicate with each other. Any message either doesn't send, or isn't relayed by the server.

_client-1_:
```
Connected to server at: 127.0.0.1:7777
Chat open:
hej
```
_client-2_:
```
Connected to server at: 127.0.0.1:7777
Chat open:
tja
hejsan!
```
_server_:
```
Opened server at: 127.0.0.1:7777
Client 127.0.0.1:51917 connected.
Client 127.0.0.1:51921 connected.
```

**Comment by azraneth** [comment]
It works. With the slight caveat of users not knowing what client they are.

**Comment by violaso** [comment]
It works well now. However, you just reduced the applications back to the same functionality-level as the original example application. The requirement for using the provided code, was to implement a new feature, which you have not done.

**Comment by azraneth** [comment]
I disagree. I've added some new functionality, I'll add the syntax to the readme.

**Comment by violaso** [comment]
Nice features, given that the client wont ever give invalid inputs. 

Question: A client can query the server to send the current number of connected clients to any client. Bug or feature? xP

```
Opened server at: 127.0.0.1:7777
Client 127.0.0.1:50533 connected.
127.0.0.1:50533: "connections hej"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:90:83
```

```
Opened server at: 127.0.0.1:7777
Client 127.0.0.1:50550 connected.
127.0.0.1:50550: "send hej"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:80:65
```

In case of error, an error message should be sent back to sending client.

**Comment by azraneth** [comment]
done
worth noting: the system cannot currently handle clients numbered higher than 9 very well
